vm-version: 'v2alpha2'
region: eu-central-1
tunnel-identifier: localdev
verbose: 0
logfile: "-"
no-ssl-bump-domains: [ all ]
tunnel-domains: [ ".httpbin.org" ]
shared-tunnel: false
proxy: localhost:8888
proxy-tunnel: false