vm-version: 'v2alpha2'
user:
api-key:
region: ${SAUCE_REGION}
tunnel-identifier: localdev
verbose: 0
logfile: "-"
no-ssl-bump-domains: [ all ]
shared-tunnel: false
#proxy-tunnel: true
#tunnel-domains: [ ".httpbin.org" ]
proxy: localhost:8180
#pac: https://gist.githubusercontent.com/kmissoumi/63d37e6c4115e3c1deaea1187fdeba87/raw