apiVersion: v1alpha
kind: imagerunner

sauce:
  concurrency: 5
  tunnel:
    name: localdev
  region: eu-central-1

suites:
  - name: photon-newman-${BUILD_ID}
    image: postman/newman_alpine33:latest
    entrypoint: "newman run https://www.getpostman.com/collections/8a0c9bc08f062d12dcda --reporters cli,json,junit"
    workload: other 
    timeout: 5m
    artifacts:
      - "/etc/newman/newman/newman-run-report*"

artifacts:
  download:
    when: always
    match:
      - "*"
    directory: ./artifacts