FROM maven:3-jdk-8-alpine

RUN apk update && apk add curl bash && rm -rf /var/cache/apk/*

ARG basePath="/usr/build"
ARG demoPath="demo-serenity/demo-serenity-junit"

ENV LANG=en_US.UTF-8
ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

WORKDIR ${basePath}/${demoPath}
COPY    ${demoPath} .

#RUN mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
#RUN ./mvnw clean verify