FROM maven:3-eclipse-temurin-17-alpine

RUN apk update && apk add curl bash && rm -rf /var/cache/apk/*

ARG basePath="/usr/build"
ARG demoPath="demo-serenity-junit"

ENV LANG=en_US.UTF-8
ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

WORKDIR ${basePath}/${demoPath}
COPY    ${demoPath} .

RUN mvn --batch-mode package --file pom.xml
#RUN mvn clean verify --file ./demo-serenity-junit/pom.xml