FROM maven:3-jdk-8-alpine

RUN apk update && apk add curl bash && rm -rf /var/cache/apk/*

ARG basePath="/usr/build"
ARG contextPath="./demo-java"
ARG SAUCE_USERNAME
ARG SAUCE_ACCESS_KEY
ARG SAUCE_REGION
ARG SAUCE_BUILD_TYPE

WORKDIR ${basePath}

ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

COPY ${contextPath}/pom.xml ${basePath}/pom.xml
COPY ${contextPath}/best-practice/pom.xml ${basePath}/best-practice/pom.xml
RUN mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

COPY ${contextPath}/best-practice ${basePath}/best-practice

#ENV JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
ENV OTEL_SDK_DISABLED=false
ENV LANG=en_US.UTF-8

RUN mvn test-compile
#RUN mvn test; exit 0
#RUN mvn -o clean package
RUN mvn --projects best-practice test -Dtest=DesktopTests; exit 0