FROM maven:3-jdk-8-alpine

RUN apk update && apk add curl bash && rm -rf /var/cache/apk/*

ARG basePath="/usr/build"
ARG contextPath="demo-java"
ARG SAUCE_USERNAME
ARG SAUCE_ACCESS_KEY
ARG SAUCE_REGION

WORKDIR ${basePath}

ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

COPY ${contextPath}/pom.xml ${basePath}/pom.xml
RUN mvn dependency:resolve

COPY ${contextPath}/src ${basePath}/src/.
RUN mvn test-compile
RUN mvn test; exit 0
RUN mvn -pl best-practice test -Dtest=DesktopTests; exit 0