FROM maven:3-jdk-8-alpine AS builder

RUN apk update && apk add curl bash && rm -rf /var/cache/apk/*

ARG basePath="/usr/build"
ARG demoPath="demo-java"


WORKDIR ${basePath}

ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

COPY ${demoPath}/pom.xml                ${basePath}/${demoPath}/pom.xml
COPY ${demoPath}/best-practice/pom.xml  ${basePath}/${demoPath}/best-practice/pom.xml
#RUN mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
#mvn dependency:go-offline


# now with less build time
# install steps cached and kept separate from test code
FROM maven:3-jdk-8-alpine

RUN apk update && apk add curl bash && rm -rf /var/cache/apk/*

ARG SAUCE_USERNAME
ARG SAUCE_ACCESS_KEY
ARG SAUCE_REGION
ARG SAUCE_BUILD_TYPE
ARG basePath="/usr/build"
ARG demoPath="demo-java"

ENV OTEL_SDK_DISABLED=false
ENV LANG=en_US.UTF-8
ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

WORKDIR ${basePath}

COPY                ${demoPath}                                     ${basePath}/${demoPath}
#COPY --from=builder ${basePath}/${demoPath}/best-practices/target   ${basePath}/${demoPath}/best-practices/target

RUN mvn test-compile
#RUN mvn test; exit 0
#RUN mvn -o clean package
RUN mvn --projects best-practice test -Dtest=DesktopTests; exit 0