FROM maven:3-eclipse-temurin-17-alpine

RUN apk --no-cache add curl bash jq tree

ARG basePath="/usr/build"
ARG demoPath="demo-serenity-junit"

ENV LANG=en_US.UTF-8
ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

WORKDIR ${basePath}/${demoPath}
COPY    ${demoPath} .

RUN mvn --batch-mode package --file pom.xml
RUN mvn clean verify --file pom.xml