#!/bin/bash -e
#
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#


downloadPath=".app"
release="1.3.0"
downloadUrl="https://github.com/saucelabs/my-demo-app-rn/releases/download/v${release}"

saucectlOptions=(--disable-usage-metrics)
saucectlOptions+=(--region ${SAUCE_REGION})
[[ -n ${SAUCE_DEBUG} ]] && saucectlOptions+=(--force)                                                           # force upload
[[ -n ${SAUCE_DEBUG} && -d ${downloadPath} ]] && mv ${downloadPath} ${downloadPath}-$(date +'%Y%m%d-%H%M%s')    # force download


demo_app_sync () {    
    mkdir -p ${downloadPath}

    # download
    [[ -f ${downloadPath}/${appRelease} ]] || curl --location ${downloadUrl}/${appRelease} --output ${downloadPath}/${appRelease} && \
        ln -f ${downloadPath}/${appRelease} ${downloadPath}/${appName}

    # upload
    saucectl storage upload ${downloadPath}/${appName} "${saucectlOptions[@]}"
} 

printf 'Syncing demo apps to Sauce Labs storage...\n'

appRelease="Android-MyDemoAppRN.1.3.0.build-244.apk"
appName="MyDemoAppRN.apk"
demo_app_sync

appRelease="iOS-Simulator-MyRNDemoApp.1.3.0-162.zip"
appName="MyRNDemoApp.zip"
demo_app_sync

appRelease="iOS-Real-Device-MyRNDemoApp.1.3.0-162.ipa"
appName="MyRNDemoApp.ipa"
demo_app_sync