#!/bin/bash -e
#
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#


downloadPath=".app"
saucectlOptions=(--disable-usage-metrics)
saucectlOptions+=(--region ${SAUCE_REGION})
[[ -n ${SAUCE_DEBUG} ]] && saucectlOptions+=(--force)                                                           # force upload
[[ -n ${SAUCE_DEBUG} && -d ${downloadPath} ]] && mv ${downloadPath} ${downloadPath}-$(date +'%Y%m%d-%H%M%s')    # force download


sync_app () {    
    [[ -d ${downloadPath} ]] || mkdir -p ${downloadPath}

    # the uploaded app name must match the filename referenced in our test
    # https://docs.saucelabs.com/dev/test-configuration-options/#appiumapp
    # 
    # take everything after the last slash that is after the first dash and before the first dot
    # concatonate with everything after the last dot...only using parameter expansion
    # only if the app name contains build or release details...
    # 

    appRelease=$(basename -- "${downloadUrl}")
    appExtension="${appRelease##*.}"
    appName=${appRelease}

    [[ ${repoPath} = "saucelabs/my-demo-app-rn" ]] && appName="${appName%%.*}" && appName="${appName##*-}" && appName="${appName}.${appExtension}"
    printf '\ndownloadUrl: %s \nappRelease: %s \nappName: %s\n' ${downloadUrl} ${appRelease} ${appName}

    # download
    [[ -f ${downloadPath}/${appRelease} ]] || curl --silent --location ${downloadUrl} --output ${downloadPath}/${appRelease}
    [[ ${appRelease} != ${appName} ]] && ln -f ${downloadPath}/${appRelease} ${downloadPath}/${appName}

    # upload
    saucectl storage upload ${downloadPath}/${appName} "${saucectlOptions[@]}"
} 


sync_release () {
    repoPath=${1}
    latestRelease=$(curl --silent "https://api.github.com/repos/${repoPath}/releases/latest")
    downloadUrls=$(jq --raw-output '.assets[].browser_download_url' <<< "${latestRelease}")

    for downloadUrl in ${downloadUrls}
        do
        sync_app
    done

}


printf 'Syncing demo apps to Sauce Labs storage...\n'
sync_release "saucelabs/my-demo-app-android"
sync_release "saucelabs/my-demo-app-ios"
printf '\n\n'