name: Gradle Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Chrome for Testing and its driver
      run: |
        npm i puppeteer
        npx @puppeteer/browsers install chrome@stable
        
    - name: Build with Gradle
      run: gradle clean test -Dheadless.mode=true
