name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          push: true
          tags: |
            suncup/photon-js:${{ GITHUB_RUN_NUMBER }} 
            suncup/photon-js:latest
      -
        name: Install saucectl
        uses: saucelabs/saucectl-run-action@v3
        with:
          saucectl-version: latest
          skip-run: true
      -
        name: Run test via Hosted Test Orchestration
        run: saucectl run --config .sauce/config-webdriver-best-practices.yml
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          SAUCE_REGION: "us-west-1"
          BUILD_TYPE: "ci-photon"
          IMAGE_TAG: ${{ GITHUB_RUN_NUMBER }}