name: Build & Test Image for Services Demo

on: [workflow_dispatch,push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image for Services Client
        uses: docker/build-push-action@v4
        with:
          context: demo-services-client/.
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          push: true
          tags: |
             suncup/photon-services-client:0.1.${{ github.run_number }}
             suncup/photon-services-client:latest

      - name: Build Image for Services Server
        uses: docker/build-push-action@v4
        with:
          context: demo-services-server/.
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          push: true
          tags: |
             suncup/photon-services-server:0.1.${{ github.run_number }}
             suncup/photon-services-server:latest
