apiVersion: v1alpha
kind: imagerunner
sauce:
  region: us-west-1
suites:
- name: my-tests
  image: sminch/mvn-so:0.0.3
  workload: webdriver
  entrypoint: "mvn test -Dtest=ChromeDesktopWeb"
  env:
    SAUCE_ENV: prod-us
    SAUCE_USERNAME: ${SAUCE_USERNAME}
    SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
    SLEEP_BEFORE_SEC: 5
    entrypoint: bash -c "wget --retry-connrefused --retry-on-http-error=400,503 -t 0 http://localhost:8032/readiness && start.sh"

  services:
  - name: squid
    image: ubuntu/squid:latest
  - name: sauce-connect
    image: saucelabs/sauce-connect:latest
    entrypoint: bash -c "http_proxy=localhost:3128 wget --retry-connrefused --retry-on-http-error=400,503 -t 0 http://saucelabs.com && start.sh"
    env:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_PROXY: "127.0.0.1:3128"
      SAUCE_PROXY_LOCALHOST: "true"
      SAUCE_CONFIG_FILE: "/sauce-connect.yml"
    files:
        - src: "sauce-connect.yml"
          dst: "/sauce-connect.yml"