# commented keys get their values from environment variables
#user:
#api-key:
#region:

verbose: 1
logfile: ./artifacts/logs/sc/app-tunnel.log
#logfile: "-"
tunnel-name: sauce-demo-app-tunnel
shared-tunnel: true
tunnel-domains:
  - api.nasa.gov
  - .saucedemo.com
no-ssl-bump-domains: all