apiVersion: v1alpha
kind: imagerunner

suites:
  - name: photon-js-build-less
    image: node:18-alpine
    resourceProfile: c3m3
    workload: other
    entrypoint: sh /bin/build-less.sh "demo-webdriverio/webdriver/best-practices" "test.saucelabs.v2"
    files:
      - src: "${PWD}/za.tar"
        dst: "/var/run/za.tar"
      - src: "${PWD}/build-less.sh"
        dst: "/bin/build-less.sh"
    env:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_REGION: ${SAUCE_REGION}
      SAUCE_BUILD_TYPE: Orchestrate Zero