apiVersion: v1alpha
kind: imagerunner

suites:
  - name: photon-js-build-less
    image: node:18-alpine
    resourceProfile: c3m3
    workload: other
    entrypoint: sh /bin/run.sh
    files:
      - src: "${PWD}/run.sh"
        dst: "/bin/run.sh"
    env:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_REGION: ${SAUCE_REGION}
      SAUCE_BUILD_TYPE: Orchestrate Zero