apiVersion: v1alpha
kind: imagerunner

suites:
  - name: photon-multipass
    image: suncup/photon-js:latest
    resourceProfile: c3m3
    workload: webdriver
    entrypoint: /bin/sh -c "pwd; ls */*/*/* > /var/log/ls4start.log; tree > /var/log/tree.log"
    artifacts:
      - "/var/log/*.log"
      - "/app/log/images/*"
    env:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_REGION: ${SAUCE_REGION}
      SAUCE_BUILD_TYPE: Orchestrate

artifacts:
  download:
    when: always
    match:
      - "*"
    directory: ./artifacts


