apiVersion: v1alpha
kind: imagerunner

# this tunnel is used by the orchestrate container
#sauce:
#  tunnel:
#    name: ${SAUCE_BACKEND_TUNNEL_NAME}

suites:
  - name: photon-js-webdriverio
    image: suncup/photon-js:latest
    resourceProfile: c3m3
    workload: webdriver
    entrypoint: npm run --prefix demo-webdriverio/webdriver/best-practices test.saucelabs.v2
    env:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_REGION: ${SAUCE_REGION}
      SAUCE_BUILD_TYPE: Orchestrate
      # this tunnel if needed used by your test code 
      # SAUCE_APP_TUNNEL_NAME: ${SAUCE_APP_TUNNEL_NAME}

